### ISSUE TITLE
Url is not reset

### ISSUE THREAD

**Issue by warpech** [Palindrom/palindrom-redirect#1] opened 2015-03-06 13:17 UTC
It seems that the following line has no effect:

``` javascript
this.setAttribute("url", "");
```

The idea for this line is that Client should reset the redirection URL after redirection was made. I think it doesn't work because it is a native Web Component, not aware of the 2-way data binding.

Proposed solution: change to Polymer element

**Comment by tomalec** [comment] 2015-03-08 15:14
I'm not sure if relying on Polymer's data binding is the best solution as it will change heavily with 0.8

What is the effect that you would like to see?
URL is reset after redirection is made in here: https://github.com/PuppetJs/puppet-redirect/blob/0.1.3/src/puppet-redirect.html#L43

Setting URL to `""` probably make no effect because of https://github.com/PuppetJs/puppet-redirect/blob/0.1.3/src/puppet-redirect.html#L22

**Comment by warpech** [comment] 2015-12-08 10:21
Sorry to not responding earlier.

The faulty line in code is still there and still doesn't work as expected: https://github.com/PuppetJs/puppet-redirect/blob/8694a54f30a405cc2de230d517442ff836fe062b/src/juicy-redirect.html#L46

The expected result is that the value of the attribute is emptied after the redirection, so it becomes possible to redirect again.

I have a handler for a form in my app (`/MyApp/new-product`). There is a following element in my HTML:

``` html
<link is="puppet-redirect" url="{{model.MorphUrl$}}" history></puppet-redirect>
```

When I change `MorphUrl$` to `/MyApp/new-product`, the UI on screen is reset.

When called for the 1st time, `puppet-redirect` successfully redirects, because `MorphUrl$` was changed (`""` -> `"/MyApp/new-product"`).

When called for the 2nd time, `puppet-redirect` fails to redirect, because this is not detected as a change (`"/MyApp/new-product"` -> `"/MyApp/new-product"`).

**Comment by tomalec** [comment] 2015-12-08 10:38
Sorry for accidental closing the issue, it was result of merging with `juicy-redirect`.

I think that clean solution would be to accept `""` as URL, and reset value to `null` after redirect. So it would perfectly fit DOM API.

However, it may require some effort on Polymer binding if it will occur that it cannot pass `null`. Plus there was an issue with returning `null` values from Starcounter https://github.com/Starcounter/Starcounter/issues/3072

**Comment by warpech** [comment] 2015-12-08 10:55
> Sorry for accidental closing the issue, it was result of merging with juicy-redirect.

Wow, so pulling changes from upstream repos closes irrelevant issues?

> I think that clean solution would be to accept "" as URL, and reset value to null after redirect.

I don't mind either `""` or null - whatever works. 

This has a low priority.

**Comment by jwillmer** [comment] 2015-12-14 08:50
I encountered that bug as well. Can someone tell me if it will be fixed in the near future or if I need to implement a workaround?

**Comment by tomalec** [comment] 2015-12-15 11:07
@jwillmer , @warpech Did I get you right, that the key problem is that `puppet-redirect` does not notify back Polymer binding -> does not change the view-model back to `""` or `null`, so it's not propagated to PuppetJs-> Starcounter?

Currently URL is reset by the element correctly, the fact that Polymer does not get it is Polymer binding problem.
The thing `this.setAttribute("url", "");` does nothing is separate issue, and even though as a clean solution I would propose that setting `url` to `""` should redirect to `""` as any other `url` value. 
But I believe due to the fact that Starcounter would not return `null`, it's better to keep current behavior.

**Comment by tomalec** [comment] 2015-12-15 11:29
If so, I created separate issue https://github.com/PuppetJs/puppet-redirect/issues/2
As regarding original issue, we won't change no effect for `this.setAttribute("url", "");`
until https://github.com/Starcounter/Starcounter/issues/3072 is done.

Once https://github.com/Starcounter/Starcounter/issues/3072 is done, we could make `puppet-redirect` do nothing for `null`, and reload the page for `""`.

**Comment by miyconst** [comment] 2016-01-11 11:47
> It seems that the following line has no effect:

``` js
this.setAttribute("url", "");
```

@warpech, unfortunately it has effect.

In the Products app on "Save" button click a redirect happens. After the redirect, the view-model which has the `RedirectUrl$` property is destroyed. And the patch 

``` json
[{"op":"replace","path":"/_ver#c$","value":2},{"op":"test","path":"/_ver#s","value":2},{"op":"replace","path":"/workspaces/0/Products/CurrentPage/Products/RedirectUrl$","value":""}]
```

is no longer valid, as there is no `RedirectUrl$` property in the new view-model.

**Comment by miyconst** [comment] 2016-01-11 12:20
This also causes `object-observe` shim craziness in IE. Because of different execution order compare to Chrome with native webcomponents and template support.

The shim can't find the observed object in the root, because it was removed from it.

**Comment by warpech** [comment] 2016-01-12 14:06
> This also causes object-observe shim craziness in IE. Because of different execution order compare to Chrome with native webcomponents and template support.
> 
> The shim can't find the observed object in the root, because it was removed from it.

Why does this happen? Shouldn't this be solved by OT? 

I agree with @miyconst's argument that sometimes the redirection replaces the view-model and then any change to the URL should be discarded. 

Maybe we can think of a better pattern? I think that the field should be read-only in the client and always cleared by the server. Then this issue becomes a non-issue.

**Comment by warpech** [comment] 2016-09-16 10:09
@Mnosek was hit my this. He will try to come up with another pattern.

**Comment by mmnosek** [comment] 2016-10-04 09:31
**My case**
In my case what I needed was to create kind of "Back" button in a mobile app, where every page has a fixed previous page. Redirection is made by puppet-redirect. So if user clicks "Back", another page is triggered by changing morph url. Because of the lack of resetting url attribute after trying to morph again to the same page as before, there is no effect (morph url is already set, so no changes = no redirect). 

**Solution**
I've managed to make it works by resetting that field on the server side every time the page is loaded. To make everything clear according to @warpech I would delete clearing the url in puppet-redirect and move the responsibility for that to the developers on the server-side. @warpech @tomalec WDYT?

**Comment by mmnosek** [comment] 2016-11-29 22:00
@tomalec @warpech ping :)

**Comment by Mihaiii** [comment] 2017-07-07 01:50
I don't know how it worked in the previous versions of Polymer that we used, but in the current one just replacing https://github.com/Palindrom/palindrom-redirect/blob/master/palindrom-redirect.html#L72 with `this.url = "";` will clear the value of the attribute and solve the general problem.

@warpech Please let me know if I should fork and make a PR.

Demo:
![redirect-demo](https://user-images.githubusercontent.com/8951553/27940574-bd70f236-62cb-11e7-8601-fc11506a6e13.gif)

**Comment by warpech** [comment] 2017-07-07 14:35
I think this is a correct solution! Before doing, please get approval from @tomalec.

Few notes here:

- note that in Polymer `xyz=""` actually sets a **property**, while `xyz$=""` sets an **attribute**.
- `palindrom-redirect` is not written with Polymer itself. It is a plain JavaScript custom element
- `palindrom-redirect` is a specialised version of https://github.com/Juicy/juicy-redirect

First, make that change in `juicy-redirect` as a PR. Then it can be pulled to `polymer-redirect` and then to the app.

If this is approved then all Starcounter samples (especially KitchenSink) `is="palindrom-redirect" url$="..."` should be changed to `is="palindrom-redirect" url="..."`

**Comment by tomalec** [comment] 2017-07-13 09:49
I don't quite get why `this.url=''` works while `this.setAttribute('url','') => this.url = ''` does not.
Is it just a hack to chanage the state of the element, without notifying Polymer?

**Comment by warpech** [comment] 2017-07-13 10:30
I don't think this is a problem with Polymer. After spending some more time on this, it surely looks like a bug in our usage of `attributeChangedCallback`.

Go to http://palindrom.github.io/palindrom-redirect/ and execute the following code in the dev tools:

```
document.querySelector("#redirect1").url = "#hey"
document.querySelector("#redirect1").url //returns "" as I would expect
document.querySelector("#redirect1").url = "#hey2"
document.querySelector("#redirect1").url //returns "#hey2", WHY!?
```

![screen shot 2017-07-13 at 12 19 39](https://user-images.githubusercontent.com/566463/28162006-eb6a16f0-67c5-11e7-9511-15b08f1fc03a.png)

The second call not return `""`, because `attributeChangedCallback` is not called for the second time. This is because the attribute already has the value `""`.

We should make it so that a change of property always updates the attribute, and a change of attribute always updates the property. So either we apply @Mihaiii's fix, or more generic, add this line after https://github.com/Palindrom/palindrom-redirect/blob/0de40a848e9a87e67a76a4714f6e444fed50abff/palindrom-redirect.html#L11:

```js
this.setAttribute("url", url)
```

**Comment by tomalec** [comment] 2017-07-13 11:34
I do vote for
> We should make it so that a change of property always updates the attribute, and a change of attribute always updates the property

But I don't see how this change is going to achieve that, I think replacing https://github.com/Palindrom/palindrom-redirect/blob/master/palindrom-redirect.html#L72 with this.url = ""; 
Makes the problem exactly opposite: it won't work with vanilla `setAttribute`/`$=`.


What about making it so:
 - setter simply sets the HTML attribute, getter gets the attribute
 - all the logic is done via `attributeChangedCallback`
?

Also the one thing that looks smelly regarding attribute vs. property symmetry is 
https://github.com/Palindrom/palindrom-redirect/blob/0de40a848e9a87e67a76a4714f6e444fed50abff/palindrom-redirect.html#L31

**Comment by warpech** [comment] 2017-07-13 11:55
> What about making it so:
>  - setter simply sets the HTML attribute, getter gets the attribute
> - all the logic is done via `attributeChangedCallback`

Good point, but from the performance perspective, I think the opposite would be more performant. HTML attributes are slower then properties: https://jsperf.com/getattribute-vs-propertyxxx

The other way round would be faster, but we cannot specify a getter for an attribute :(

**Comment by tomalec** [comment] 2017-07-13 18:11
I do agree attribute is slower than property, but given that we actually want "to set/get attribute every time property is set/get", symmetrically "we actually want to set/get property every time attribute is set/get", I don't see how would you like to get any performance gain by doing the opposite - always we will have to set/get property AND attribute

**Comment by tomalec** [comment] 2017-07-13 18:13
PS. That's why Polymer by default uses properties only, and warns devs that using and reflecting the attributes is expensive (even though, that's real "DOM is the API" approach IMO)

**Comment by warpech** [comment] 2017-07-18 11:34
> I don't see how would you like to get any performance gain by doing the opposite - always we will have to set/get property AND attribute

There is no performance gain for the `set` operation, but there is performance gain for the `get` operation if you are reading from the property.

Anyway... @Mihaiii did you get anything from this? :D

**Comment by Mihaiii** [comment] 2017-07-18 11:48
> Anyway... @Mihaiii did you get anything from this? :D

:) I don't think "$=" will work no matter the changes on `palindrom-redirect`/`puppet-redirect`. For it to work, I think we need to use `reflectToAttribute`.

Can't we just use what you proposed?

> more generic, add this line after https://github.com/Palindrom/palindrom-redirect/blob/0de40a848e9a87e67a76a4714f6e444fed50abff/palindrom-redirect.html#L11:
> 
> this.setAttribute("url", url)

**Comment by warpech** [comment] 2017-07-18 12:00
I think that @tomalec's proposal is better:

> What about making it so:
>
> - setter simply sets the HTML attribute, getter gets the attribute
> - all the logic is done via attributeChangedCallback

Please make that change as a PR in https://github.com/juicy/juicy-redirect

**Comment by warpech** [comment] 2017-07-25 14:11
@Mihaiii thanks for fixing this in https://github.com/Juicy/juicy-redirect/pull/6

Proposal of the next steps (@tomalec WDYT of the proposed version numbering?):

1. Release a version `0.6.0` of `juicy-redirect` (skip `0.5.0` because that was released only in `palindrom-redirect`)
2. Merge `juicy-redirect master` to `palindrom-redirect master`
3. Release a version `0.6.0` of `palindrom-redirect`
4. Include version `0.6.0` of `palindrom-redirect` also aliased `puppet-redirect` in Starcounter 2.3.x
5. Update `puppet-redirect`/`palindrom-redirect` in all relevant apps and close this issue - by this I mean change `url$=""` to `url=""`

**Comment by warpech** [comment] 2017-08-07 08:47
Ping

**Comment by warpech** [comment] 2017-10-02 22:49
@PatrykSzwer can you please apply the steps from https://github.com/Palindrom/palindrom-redirect/issues/1#issuecomment-317749961

**Comment by PatrykSzwer** [comment] 2017-10-03 08:11
I've just released `juicy-redirect` in version `0.6.0`

**Comment by warpech** [comment] 2017-10-16 09:07
@PatrykSzwer can you pls continue with the steps 2-5 from https://github.com/Palindrom/palindrom-redirect/issues/1#issuecomment-317749961?

**Comment by PatrykSzwer** [comment] 2017-10-16 10:34
I've created PR for 2nd step in palindrom-redirect repository.

**Comment by warpech** [comment] 2017-10-17 10:52
> I've created PR for 2nd step in palindrom-redirect repository.

For reference: https://github.com/Palindrom/palindrom-redirect/pull/7

**Comment by warpech** [comment] 2017-10-18 15:15
@PatrykSzwer is this done?

In future please always do a separate Git commit for bumping the version number. Do not set a Git tag on a merge commit.

**Comment by PatrykSzwer** [comment] 2017-10-18 15:34
> In future please always do a separate Git commit for bumping the version number. Do not set a Git tag on a merge commit.

~~???
I though I always doing that. Where I forgot to do it?~~
Nvm, now I see. I didn't noticed that here is another commit after my with version, and I set it automatically on the latest. I'll remember to double check this always in future. Can I fix it somehow or It's too late now?

About https://github.com/Palindrom/palindrom-redirect/issues/1#issuecomment-317749961, I'm currently working on step 4.

**Comment by warpech** [comment] 2017-10-18 19:48
> Can I fix it somehow or It's too late now?

Maybe make an empty commit `0.6.0` or `palindrom-redirect 0.6.0` (to distinguish from `juicy-redirect` 0.6.0) and move the Git tag to it?

**Comment by PatrykSzwer** [comment] 2017-10-19 08:33
> Maybe make an empty commit 0.6.0 or palindrom-redirect 0.6.0 (to distinguish from juicy-redirect 0.6.0) and move the Git tag to it?

Done.

**Comment by Mihaiii** [comment] 2017-10-23 17:17
Hi guys!
While doing the review, I noticed there are some problems because of some extra calls to get the property (that, in its turn, gets the attribute and the last set on that attribute is an empty string) and I end up with `Invalid frame header`.

**Comment by Mihaiii** [comment] 2017-10-23 18:34
The way I see it, there shoul be only one `juicy-redirect`: on MasterPage. Would this be problematic?

**Comment by warpech** [comment] 2017-10-24 08:34
`Invalid frame header` is not a bug itself. It is a manifestation that there was an unhandled exception in C# Palindrom (main issue: https://github.com/Starcounter/Home/issues/174). You should see the exact error in Administrator. Can you check that?

**Comment by Mihaiii** [comment] 2017-10-24 08:49
> "Starcounter.XSON.JsonPatchException: Property 'RedirectUrl' is readonly. Patch: '{"op":"replace","path":"/UserAdmin_0/CurrentPage/RedirectUrl","value":""}'. Viewmodel versions: {client (_ver#c$): 2, clients serverversion: 2, server (_ver#s): 2}.
>    at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9598\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 24
>    at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9598\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 605
>    at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9598\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 526
>    at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9598\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 414
>    at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9598\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 69
> Patch={"op":"replace","path":"/UserAdmin_0/CurrentPage/RedirectUrl","value":""}
> Severity=1
> HResult=-2146233088"

I added the "$" to "RedirectUrl", but it doesn't redirect now, probably because "puppet-redirect" shouldn't do nothing if the `url` is an empty string.

**Comment by PatrykSzwer** [comment] 2017-10-24 08:51
@Mihaiii please check my comment here: https://github.com/StarcounterApps/UserAdmin/pull/91#event-1305515515

**Comment by Mihaiii** [comment] 2017-10-24 09:00
Answered. :)

**Comment by warpech** [comment] 2017-10-24 09:40
Just to make sure, the intended data flow is like this:

- in some apps, there is a single instance of `palindrom-redirect` in the `MasterPage.html` that is kept during the whole session lifecycle
- whenever server wants to force the client to navigate to another URI, it sets `RedirectUrl$` value to that URI
- the client receives the new value, redirects to that URI and resets the URI to an empty string. 
- the main purpose of resetting to an empty string is to be able to redirect to the same URI multiple times (`"/people"` > `""` > `"/people"`). Without empty string, redirecting from `/people` to `/people` is not possible because Polymer does not detect it as a change.

Does it help? Should it be added to `palindrom-redirect` readme?

**Comment by PatrykSzwer** [comment] 2017-10-24 09:49
I fixed invalid frame header problem in UserAdmin. I'll check rest of my PRs for that issue, and fix it if needed.

**Comment by Mihaiii** [comment] 2017-10-24 09:51
>> in some apps, there is a single instance of palindrom-redirect in the MasterPage.html that is kept during the whole session lifecycle

Should this be a standard in all the apps? On one hand, it makes a lot of sense, on another, won't it affect blending?

**Comment by PatrykSzwer** [comment] 2017-10-24 12:57
I think I've covered all apps with this change. Please check if I didn't miss any of them.

**Comment by Mihaiii** [comment] 2017-10-24 20:00
> I think I've covered all apps with this change. Please check if I didn't miss any of them.

1. Please ~~update~~ review CssVariablesManager ~~too~~.
2. I think we should include `palindrom-redirect` in `ignoredDependencies` for all the apps, but that's another issue. I'll take this one.

By the way, thank you for also covering the apps under `apps-team`!

**Comment by PatrykSzwer** [comment] 2017-10-25 09:15
> 1. Please update review CssVariablesManager too.

Done.
When all PR's will be merged, I'll close this issue. Thank you for taking care of `ignoredDependencies`!

**Comment by PatrykSzwer** [comment] 2017-10-25 10:41
Since all related PRs are merged, and all steps from https://github.com/Palindrom/palindrom-redirect/issues/1#issuecomment-317749961 are finished, I'm closing this issue.

**Comment by Mihaiii** [comment] 2017-10-26 21:13
Meh, I can't reopen this issue.

Do you think we still need backward compatibility ?

>                 /* backward compatibility */
>                 this.dispatchEvent(
>                     new CustomEvent(
>                         "puppet-redirect-pushstate",
>                         {
>                             "detail":{"url":url},
>                             "bubbles": true
>                         }
>                     )
>                 );

I'm asking because this event triggers Handle.GET a second time, ending up with a beautiful error (`ScErrTransactionClosed (SCERR4260): An operation failed because transaction has been closed.
`) when website app is running (it is not website's fault because it triggers it 2 times even if Website app is not running, but without any error).

I apologize for not noticing this while doing the review (I didn't had Website app running all the time).

**Comment by Mihaiii** [comment] 2017-10-26 21:13
@warpech , @tomalec Please see the above message. Thank you!

**Comment by Mihaiii** [comment] 2017-10-26 21:17
Steps to reproduce:
1. Run Barcodes
2. Run Website
3. Navigate to `/barcodes/barcodes/`
4. Click "Cancel" (here Handle.GET("/barcodes/barcodes", () => {...}) gets 2 code hits)
5. Click "Add new barcode"
6. Click "Cancel"

**Comment by warpech** [comment] 2017-11-08 20:53
@PatrykSzwer can you pls take a look? What is the reason of the broken compatibility?

**Comment by PatrykSzwer** [comment] 2017-11-09 12:19
I think this may be related to https://github.com/Starcounter/Website/issues/264. I'll check further

**Comment by PatrykSzwer** [comment] 2017-11-09 13:02
Yes, I can confirm that both Starcounter/Website#264 and issue above have same solution - removing `history` tag. But in case of website `develop` there is no another unexpected call for the Uri handler. I don't really know whats causing this situation. 
As description says in palindrom/juicy-redirect about `history` attr:
`If attribute history is present, the History API pushState is used instead of window.location`
Question is when this is really needed?

**Comment by Mihaiii** [comment] 2017-11-09 13:12
Like I said, we dispatch both [palindrom-redirect-pushstate](https://github.com/Palindrom/palindrom-redirect/blob/master/palindrom-redirect.html#L47) and right after that, for backward compatibility, [puppet-redirect-pushstate](https://github.com/Palindrom/palindrom-redirect/blob/master/palindrom-redirect.html#L57) and also for backward compatibility we listen to both of them.

Therefore, the solution without removing the `history` attribute would be to dispatch only one event and therefore [this line](https://github.com/Starcounter/level1/blob/d96c772d5bb9e05c6e1dbc6539f6828c3d755bf6/src/BuildSystem/ClientFiles/StaticFiles/sys/Palindrom/dist/palindrom-dom.js#L4786) won't get a code hit twice, resulting in Self.GET not getting triggered twice.

**Comment by alshakero** [comment] 2017-11-15 16:54
Is this done?

**Comment by Mihaiii** [comment] 2017-11-15 17:57
Yup, can be closed imo.

Thanks for reopening!

**Closed as completed** 2017-11-15 18:03 UTC
Labels: bug
