### ISSUE TITLE
No request is triggered if viewmodel already contains a value for redirection.

### ISSUE THREAD

**Issue by chrhol** [Palindrom/palindrom-redirect#4] opened 2017-02-23 13:21 UTC
If the first response containg the viewmodel already have an uri set for redirect, only the addressbar/history is updated. No request is sent.

My suspicion is that `puppet-redirect` triggers the `puppet-redirect-pushstate` event before `puppet-js` have added the listener.

cc @warpech, @malx122

### Expected result
The addressbar updated with the already set uri.
The already set uri should trigger a request.

### Actual result
The addressbar updated with the already set uri.
No request is triggered.

### Browsers affected
Only tested in Chrome. 

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot
![dev-tools-redirect](https://cloud.githubusercontent.com/assets/1658979/23260570/bd7e0d98-f9d2-11e6-89ad-778b187ff253.JPG)

![white-redirect](https://cloud.githubusercontent.com/assets/1658979/23260644/179038ce-f9d3-11e6-9151-0aa695af629e.JPG)

**Comment by malx122** [comment] 2017-02-23 13:53
Yepp, sending the event is not received.
Tested a manual workaround and let puppet-redirect call puppet script directly instead of sending an event:
```
  puppet.puppet.morphUrl(url);
  /* this.dispatchEvent(
                    new CustomEvent(
                        "puppet-redirect-pushstate",
                        {
                            "detail":{"url":url},
                            "bubbles": true
                        }
                    )
                );*/
```
That work!

**Comment by malx122** [comment] 2017-02-23 13:56
This is high prio @warpech because it affects all our customer servers. The workaround is implemented manual on some of our servers now, but of course need to be applied for every new SC installation.

**Comment by warpech** [comment] 2017-02-23 17:59
I tried to reproduce it in KitchenSink but it works OK there.

1. In `src/KitchenSink/RedirectPage.json`, change line 10 to be: `"RedirectUrl$": "/kitchensink"`
2. Build and run KitchenSink
3. Go to http://localhost:8080/kitchensink/redirect in your browser

Redirection works as expected.

@malx122 do you have some idea what is the difference? Are you running current versions of `puppet-redirect` and PuppetJs?

I need a way to reproduce it before I can diagnose the problem.

**Comment by chrhol** [comment] 2017-02-24 08:38
I will try as well. Maybe it's working because in KitchenSink, the redirectpage is a partial and the redirect is not directly specified in the masterpage.

**Comment by chrhol** [comment] 2017-02-24 10:59
@warpech: I added a sample, https://github.com/chrhol/RedirectApp, where this can be reproduced (at least on my machine). 

Start and go to http://localhost:8080/RedirectApp.

You should see the addressbar being updated (http://localhost:8080/RedirectApp/redirect) but no request to the new url.

**Comment by alshakero** [comment] 2017-02-24 11:17
@warpech can I take care of this? I would like to understand the way we manage redirects.

**Comment by warpech** [comment] 2017-02-24 11:25
Yes, for now I am carrying the investigation. I will update the issue when I have more info.

**Comment by warpech** [comment] 2017-02-24 11:41
> You should see the addressbar being updated (http://localhost:8080/RedirectApp/redirect) but no request to the new url.

In your example the reason is different. The initial page is not bootstrapped correctly. It can be bootstraped using `PartialToStandaloneHtmlProvider`.

I have made a PR: https://github.com/chrhol/RedirectApp/pull/1. After my fix, the original problem is not reproducible.

@chrhol any ideas what's the reason now?

**Comment by warpech** [comment] 2017-02-24 12:03
I think I know what is going on. Colabers (and https://github.com/chrhol/RedirectApp `master` branch) does not use `PartialToStandaloneHtmlProvider`.

`PartialToStandaloneHtmlProvider` wraps everything, even `Master.html` in a `<template is="imported-template">`, which loads the view asynchronously. Without `PartialToStandaloneHtmlProvider`, the master view is bootstrapped synchronously, causing `puppet-redirect` to execute before PuppetDOM starts to listen for the events.

I will work on proposing a solution to this.

**Comment by warpech** [comment] 2017-02-24 12:05
The problem is solved when you move:

```js
      if (puppet.onDataReady) {
        puppet.onDataReady.call(puppet, puppet.obj);
      }
```

to the first line after `reconnectionFn(function bootstrap(responseText){` in `puppet.js` file.

**Comment by warpech** [comment] 2017-02-24 12:16
@malx122 could you pls confirm the above fix? Can you live with this as a temporary solution for a week or two? We are now doing a big rework of PuppetJs aka Palindrom (https://github.com/PuppetJs/PuppetJs/issues/118) and I would like to solve this afterwards.

Thanks a lot @chrhol for helping to isolate the problem. This problem needs solving in Puppet/Palindrom (not in `puppet-redirect`, not in the app).

**Comment by malx122** [comment] 2017-02-24 12:32
Om sorry, I will not have time to confirm today, going hunting this weekend. The reason I dont want a manual workaround is that we have so many problem som with 2.3 that we reinstall new versions all the time for the moment...

**Comment by warpech** [comment] 2017-02-24 12:39
Git blame suggests to me that this problem exists at least since July 2016 (https://github.com/PuppetJs/PuppetJs/blame/master/src/puppet.js#L493-L501). Any idea why it has not surfaced earlier?

**Comment by alshakero** [comment] 2017-03-14 18:01
For everyone's information https://github.com/Palindrom/Palindrom/releases/tag/2.4.1

**Comment by warpech** [comment] 2017-03-14 18:20
Closing as fixed. To know when it is included in Starcounter, follow https://github.com/Starcounter/Starcounter/issues/4147.

There was no change in `puppet-redirect`, just a change in PuppetJs.

**Closed as completed by warpech** 2017-03-14 18:20 UTC
Labels: bug
